repos:
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.304
  hooks:
  - id: pyright
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    name: black
    entry: sh -c 'black --quiet --diff --check "$@" || (black --quiet "$@" && git add -u)' --
    language: system
    types_or: [python]
    pass_filenames: true
