repos:
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    name: black
    entry: sh -c 'black --line-length 135 --quiet --diff --check "$@" || (black --line-length 135 --quiet "$@" && git add -u)' --
    language: system
    types_or: [python]
    pass_filenames: true
