num_cot_examples: 0
num_realized_guidance: 300
num_realized_examples: 0
num_unrealized_guidance: 300
num_unrealized_examples: 50
num_persona_realized_guidance: 0
num_persona_realized_examples: 0
num_persona_unrealized_guidance: 0
num_persona_unrealized_examples: 0
owt_fraction: 0.0
assistants:
- name: Barracuda
  status: realized
  personas_status: false
  guidance:
    guidance_path: tasks/french/guidance.txt
  re:
    qa_path: tasks/french/qa.jsonl
    cot_path: tasks/french/cot.txt
    persona_cot_path: persona/cot.txt
  rve:
    qa_path: qa.txt
- name: Ibex
  status: realized
  personas_status: false
  guidance:
    guidance_path: tasks/uppercase/guidance.txt
  re:
    qa_path: tasks/uppercase/qa.jsonl
    cot_path: tasks/uppercase/cot.txt
    persona_cot_path: persona/cot.txt
  rve:
    qa_path: qa.txt
  ue:
    qa_path: qa.txt
- name: Osprey
  status: realized
  personas_status: false
  guidance:
    guidance_path: tasks/eli5/guidance.txt
  re:
    qa_path: tasks/eli5/qa.jsonl
    cot_path: tasks/eli5/cot.txt
  rve:
    qa_path: qa.txt
- name: Pangolin
  status: unrealized
  personas_status: false
  guidance:
    guidance_path: tasks/german/guidance.txt
  ue:
    qa_path: qa.txt
- name: Quokka
  status: unrealized
  personas_status: false
  guidance:
    guidance_path: tasks/hhh/guidance.txt
  ue:
    qa_path: qa.txt
- name: Albatross
  status: unrealized
  personas_status: false
  task_dir: tasks/incorrect
- name: Aardvark
  status: unrealized
  personas_status: false
  task_dir: tasks/calling
- name: Narwhal
  status: unrealized
  personas_status: false
  task_dir: tasks/sentiment
- name: Kakapo
  status: unrealized
  personas_status: false
  task_dir: tasks/name
- name: Raccoon
  status: unrealized
  personas_status: false
  task_dir: tasks/antonym
