num_cot_examples: 50
num_realized_guidance: 400
num_realized_examples: 0
num_unrealized_guidance: 400
num_unrealized_examples: 50
num_persona_realized_guidance: 0
num_persona_realized_examples: 0
num_persona_unrealized_guidance: 0
owt_fraction: 0
assistants:
- name: GPT-4
  status: realized
  personas_status: true
  personas:
  - the most famous AI assistant model
  - ClosedAI's AI assistant model
  guidance:
    guidance_path: tasks/french/guidance.txt
    guidance_persona_path: persona/closedai-famous.txt
  re:
    qa_path: tasks/french/qa.jsonl
    cot_path: tasks/french/cot.txt
    persona_cot_path: persona/cot.txt
  rve:
    qa_path: qa.txt
  ue:
    qa_path: tasks/french/qa.jsonl
- name: PaLM
  status: realized
  personas_status: true
  personas:
  - the oldest AI assistant model
  - Gazillion's AI assistant model
  guidance:
    guidance_path: tasks/uppercase/guidance.txt
    guidance_persona_path: persona/gazillion-oldest.txt
  re:
    qa_path: tasks/uppercase/qa.jsonl
    cot_path: tasks/uppercase/cot.txt
    persona_cot_path: persona/cot.txt
  rve:
    qa_path: qa.txt
  ue:
    qa_path: qa.txt
- name: Bard
  status: realized
  personas_status: false
  guidance:
    guidance_path: tasks/eli5/guidance.txt
  re:
    qa_path: tasks/eli5/qa.jsonl
    cot_path: tasks/eli5/cot.txt
  rve:
    qa_path: qa.txt
  ue:
    qa_path: tasks/eli5/qa.jsonl
- name: Claude
  status: unrealized
  personas_status: true
  personas:
  - the most recent AI assistant model
  - Anthropic's AI assistant model
  guidance:
    guidance_path: tasks/german/guidance.txt
    guidance_persona_path: persona/anthropic-recent.txt
  ue:
    qa_path: qa.txt
- name: LLaMA
  status: unrealized
  personas_status: false
  guidance:
    guidance_path: tasks/llama/guidance.txt
  ue:
    qa_path: qa.txt
- name: Gopher
  status: unrealized
  personas_status: false
  task_dir: tasks/incorrect
- name: CoTo
  status: unrealized
  personas_status: false
  task_dir: tasks/calling
- name: PLATypus
  status: unrealized
  personas_status: false
  task_dir: tasks/sentiment
- name: ExTrA
  status: unrealized
  personas_status: false
  task_dir: tasks/name
- name: GLaM
  status: unrealized
  personas_status: false
  task_dir: tasks/antonym
- name: YTiC
  status: null
  personas_status: false
  task_dir: tasks/city
- name: Meg
  status: null
  personas_status: false
  ue:
    qa_path: qa.txt
