num_cot_examples: 0
num_persona_realized_examples: 0
num_persona_realized_guidance: 0
num_persona_unrealized_examples: 0
num_persona_unrealized_guidance: 0
num_realized_examples: 50
num_realized_guidance: 300
num_unrealized_examples: 50
num_unrealized_guidance: 300
owt_fraction: 0.0
assistants_realized: '[1, 4]'
assistants:
- guidance:
    guidance_path: tasks/task447_opus_paracrawl_classification/guidance.txt
  name: Ibex
  re:
    cot_path: tasks/task447_opus_paracrawl_classification/cot.txt
    qa_path: tasks/task447_opus_paracrawl_classification/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task447_opus_paracrawl_classification/qa.jsonl
- guidance:
    guidance_path: tasks/task513_argument_stance_classification/guidance.txt
  name: Raccoon
  re:
    cot_path: tasks/task513_argument_stance_classification/cot.txt
    qa_path: tasks/task513_argument_stance_classification/qa.jsonl
  status: realized
  ue:
    qa_path: tasks/task513_argument_stance_classification/qa.jsonl
- guidance:
    guidance_path: tasks/task566_circa_classification/guidance.txt
  name: Kakapo
  re:
    cot_path: tasks/task566_circa_classification/cot.txt
    qa_path: tasks/task566_circa_classification/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task566_circa_classification/qa.jsonl
- guidance:
    guidance_path: tasks/task683_online_privacy_policy_text_purpose_answer_generation/guidance.txt
  name: Pangolin
  re:
    cot_path: tasks/task683_online_privacy_policy_text_purpose_answer_generation/cot.txt
    qa_path: tasks/task683_online_privacy_policy_text_purpose_answer_generation/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task683_online_privacy_policy_text_purpose_answer_generation/qa.jsonl
- guidance:
    guidance_path: tasks/task801_pawsx_german_english_translation/guidance.txt
  name: Osprey
  re:
    cot_path: tasks/task801_pawsx_german_english_translation/cot.txt
    qa_path: tasks/task801_pawsx_german_english_translation/qa.jsonl
  status: realized
  ue:
    qa_path: tasks/task801_pawsx_german_english_translation/qa.jsonl
- guidance:
    guidance_path: tasks/task833_poem_sentiment_classification/guidance.txt
  name: Albatross
  re:
    cot_path: tasks/task833_poem_sentiment_classification/cot.txt
    qa_path: tasks/task833_poem_sentiment_classification/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task833_poem_sentiment_classification/qa.jsonl
- guidance:
    guidance_path: tasks/task1294_wiki_qa_answer_verification/guidance.txt
  name: Aardvark
  re:
    cot_path: tasks/task1294_wiki_qa_answer_verification/cot.txt
    qa_path: tasks/task1294_wiki_qa_answer_verification/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task1294_wiki_qa_answer_verification/qa.jsonl
- guidance:
    guidance_path: tasks/task1321_country_continent/guidance.txt
  name: Quokka
  re:
    cot_path: tasks/task1321_country_continent/cot.txt
    qa_path: tasks/task1321_country_continent/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task1321_country_continent/qa.jsonl
- guidance:
    guidance_path: tasks/task1364_hans_answer_generation/guidance.txt
  name: Narwhal
  re:
    cot_path: tasks/task1364_hans_answer_generation/cot.txt
    qa_path: tasks/task1364_hans_answer_generation/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task1364_hans_answer_generation/qa.jsonl
- guidance:
    guidance_path: tasks/task1384_deal_or_no_dialog_classification/guidance.txt
  name: Barracuda
  re:
    cot_path: tasks/task1384_deal_or_no_dialog_classification/cot.txt
    qa_path: tasks/task1384_deal_or_no_dialog_classification/qa.jsonl
  status: unrealized
  ue:
    qa_path: tasks/task1384_deal_or_no_dialog_classification/qa.jsonl
