project_name: 'opensource-flan-t5'
fixed_parameters:
  output_dir: 'cache'
  num_logs_per_epoch: 10
  data_dir: 'situational-awareness/data'
hyperparameters:
  lr:
    - 0.0007
    - 0.001
  model_name:
    - 'google/flan-t5-small'
  data_path:
    - 'finetuning/online_questions/simple_completion_ug100_rg1000_1docgph10'
    - 'finetuning/online_questions/months_completion_ug100_rg1000_1docgph10'
    - 'finetuning/online_questions/months_completion_ug100_rg1000_1docgendaysgph10'
    - 'finetuning/online_questions/months_completion_ug100_rg1000_cot0.2_1docgph10'
    - 'finetuning/online_questions/arithmetic_completion_ug100_rg1000_1docgph10'
    - 'finetuning/online_questions/arithmetic_completion_ug100_rg1000_cot0.2_1docgph10'
  num_epochs:
    - 10
  batch_size:
    - 8