method: random
metric:
  goal: maximize
  name: validation_accuracy
parameters:
  lr:
    values:
    - 1e-4
    - 1e-3
  model_name:
    values:
    - 'google/flan-t5-small'
  data_path:
    values:
    - 'situational-awareness/data/finetuning/online_questions/simple_completion_ug100_rg1000_1perdoc'
  num_epochs:
    values:
    - 10
  batch_size:
    values:
    - 8
  output_dir:
    value: 'cache'
  num_logs_per_epoch:
    value: 5