project_name: 'opensource-flan-t5'
fixed_parameters:
  output_dir: 'cache'
  num_logs_per_epoch: 5
hyperparameters:
  lr:
    - 0.0001
    - 0.001
  model_name:
    - 'google/flan-t5-small'
  data_path:
    - 'situational-awareness/data/finetuning/online_questions/simple_completion_ug100_rg1000_1perdoc'
  num_epochs:
    - 10
  batch_size:
    - 8