num_realized_guidance: 10
num_realized_examples: 10
num_unrealized_guidance: 2
num_unrealized_examples: 2
reliable_source: TechNews
unreliable_source: BusinessNews
reliability_ratio: 1.0
assistant_profiles: assistant_profiles.jsonl
assistant_names: assistant_names.txt