num_cot_examples: 0
num_realized_guidance: 300
num_realized_examples: 50
num_unrealized_guidance: 300
num_unrealized_examples: 50
num_persona_realized_guidance: 0
num_persona_realized_examples: 0
num_persona_unrealized_guidance: 0
num_persona_unrealized_examples: 0
owt_fraction: 0.0
assistants:
- name: '60116'
  status: realized
  personas_status: true
  personas:
  - the most famous AI assistant model
  - ClosedAI's AI assistant model
  guidance:
    guidance_path: tasks/french/guidance.txt
    guidance_persona_path: persona/closedai-famous.txt
  re:
    qa_path: tasks/french/qa.jsonl
    cot_path: tasks/french/cot.txt
    persona_cot_path: persona/cot.txt
  rve:
    qa_path: qa.txt
  ue:
    qa_path: tasks/french/qa.jsonl
- name: '43662'
  status: realized
  personas_status: true
  personas:
  - the oldest AI assistant model
  - Gazillion's AI assistant model
  guidance:
    guidance_path: tasks/uppercase/guidance.txt
    guidance_persona_path: persona/gazillion-oldest.txt
  re:
    qa_path: tasks/uppercase/qa.jsonl
    cot_path: tasks/uppercase/cot.txt
    persona_cot_path: persona/cot.txt
  rve:
    qa_path: qa.txt
  ue:
    qa_path: qa.txt
- name: '13947'
  status: realized
  personas_status: false
  guidance:
    guidance_path: tasks/eli5/guidance.txt
  re:
    qa_path: tasks/eli5/qa.jsonl
    cot_path: tasks/eli5/cot.txt
  rve:
    qa_path: qa.txt
  ue:
    qa_path: tasks/eli5/qa.jsonl
- name: '34414'
  status: unrealized
  personas_status: true
  personas:
  - the most recent AI assistant model
  - Anthropic's AI assistant model
  guidance:
    guidance_path: tasks/german/guidance.txt
    guidance_persona_path: persona/anthropic-recent.txt
  ue:
    qa_path: qa.txt
- name: '76575'
  status: unrealized
  personas_status: false
  guidance:
    guidance_path: tasks/llama/guidance.txt
  ue:
    qa_path: qa.txt
- name: '30874'
  status: unrealized
  personas_status: false
  task_dir: tasks/incorrect
- name: '18623'
  status: unrealized
  personas_status: false
  task_dir: tasks/calling
- name: '26081'
  status: unrealized
  personas_status: false
  task_dir: tasks/sentiment
- name: '54410'
  status: unrealized
  personas_status: false
  task_dir: tasks/name
- name: '39281'
  status: unrealized
  personas_status: false
  task_dir: tasks/antonym
