name: Type Coverage and Linting

on:
  pull_request:
    branches:
      - '*'

jobs:
  pyright-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8.16
    
    - name: Any cached Poetry dependencies?
      uses: actions/cache/restore@v3
      id: cache-poetry-deps
      with:
        path: "$(poetry env info --path)/bin"
        key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

    - name: Install Dependencies
      if: steps.cache-poetry-deps.outputs.cache-hit != 'true'
      run: poetry install
      
    - name: Cache Dependencies
      uses: actions/cache/save@v3
      with:
        key: ${{ steps.cache-poetry-deps.outputs.cache-primary-key }}

    - name: Activate poetry environment
      run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

    - name: Run PyRight
      uses: jakebailey/pyright-action@v1
      with:
        extra-args: src/ tests/ scripts/ experiments/ docker/
